## Importing libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import uuid
import warnings
warnings.filterwarnings('ignore')

## Data collection

In [3]:
df = pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/7223570/11518162/River_Plastic_Waste_Risk_Scenarios_2015_2060.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250526%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250526T042543Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=78ae48ad82807a3662eec2f1e1efae38b44072ae45bce9a715ac976309bd74025de5d832eb10d6a96c99ed4d8e0566520e71f07770228b3cdc773b9dc47eb94f6d1d8251dbf40371be2434b7dbeeb54b5a6787f02aa06964aa7fd41eec621b921fef4be77c6dca1ef82a685b06dde63cc5295b9366ebdabfc8d8f9ac7ae5c934f1e2661461bcf9c0de04e83e057443b5a43c1c2eb70f7f2a22332a766a5516d51e92e611021883ebb31a269ddf5781892838cdfe246e3081b62161e06045e6e2905b4fdab1b4e9c648a65aace7b6d8f945812b89eddd9ca49114455bb41ee8d33db63be63606c55f092db4ee9828f31226615ac682e6b3c639c86ebaacfc2b2b')

In [6]:
# Display the first few rows of the dataset
df.head()

,River_ID,River_Name,Country,Continent,Population_2015,Population_2060,Waste_Generation_2015_tons,Waste_Generation_2060_tons,Plastic_Waste_2015_tons,Plastic_Waste_2060_tons,...,Basin_Area_km2,Urbanization_2015_pct,Urbanization_2060_pct,GDP_per_capita_2015,GDP_per_capita_2060,Policy_Strength_2015,Policy_Strength_2060,Waste_Collection_Rate_2015,Waste_Collection_Rate_2060,Risk_Score_Change
0,1,River_0,Brazil,South America,16194478,26111907,17792.200652,19741.088429,2334.317226,3190.490009,...,416388.877759,32.740347,40.467721,4993.410491,7967.060920,0.524756,0.797534,0.403860,0.606824,-393.971968
1,2,River_1,Vietnam,Asia,13337723,23762872,9773.501161,16410.792306,2186.109392,3716.919707,...,7619.215619,76.532105,89.981429,9942.704312,12137.617217,0.230894,0.427304,0.678284,0.880784,-226.234377
2,3,River_2,USA,North America,13579854,16585826,12100.472956,12974.031643,3038.093359,3049.301900,...,198179.967765,75.599532,91.508612,8500.248836,16503.889051,0.520834,1.000000,0.791174,1.000000,211.992452
3,4,River_3,DR Congo,Africa,2804238,4711445,2402.540235,4150.474491,501.023859,739.551654,...,3755.536445,68.927686,84.530546,18360.675617,40442.168783,0.074045,0.317431,0.281108,0.546884,-81.894650
4,5,River_4,Nigeria,Africa,17873323,23800628,10072.660424,21681.951354,1662.358278,6416.149836,...,380631.739260,53.676632,70.241140,12597.992111,23678.589812,0.427541,0.537709,0.275524,0.333381,61.485910

In [10]:
# Display summary statistics of the dataset
df.describe()

,River_ID,Population_2015,Population_2060,Waste_Generation_2015_tons,Waste_Generation_2060_tons,Plastic_Waste_2015_tons,Plastic_Waste_2060_tons,Mismanaged_Waste_2015_tons,Mismanaged_Waste_2060_tons,Plastic_to_River_2015_tons,...,Basin_Area_km2,Urbanization_2015_pct,Urbanization_2060_pct,GDP_per_capita_2015,GDP_per_capita_2060,Policy_Strength_2015,Policy_Strength_2060,Waste_Collection_Rate_2015,Waste_Collection_Rate_2060,Risk_Score_Change
count,3000.000000,3.000000e+03,3.000000e+03,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,...,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,9.902995e+06,1.439333e+07,9937.108593,15722.462520,1972.420450,3944.802205,984.794046,1599.795419,246.130444,...,255050.174161,50.057792,62.708560,12788.280554,23538.089370,0.497450,0.741778,0.553076,0.720815,35.788421
std,866.169729,5.768554e+06,8.701584e+06,6695.912177,10601.295790,1486.016108,2857.043089,792.936969,1292.345791,225.795829,...,145043.553125,17.206687,17.699645,6983.325528,13866.334802,0.287451,0.248651,0.199433,0.200259,280.864915
min,1.000000,1.002450e+05,1.488670e+05,97.433964,112.888574,17.274615,24.166990,7.181986,5.941984,1.340865,...,1224.065038,20.000332,25.893246,521.003622,765.286423,0.000125,0.110998,0.200072,0.256240,-1246.002148
25%,750.750000,4.877241e+06,6.893512e+06,4430.943455,7201.296054,825.059031,1713.877218,369.395386,634.996615,81.662342,...,128174.188742,35.462172,48.265934,6834.986397,11996.601860,0.248929,0.537364,0.385712,0.559278,-78.293886
50%,1500.500000,9.838680e+06,1.410217e+07,9107.858721,14318.548919,1665.601032,3441.779457,797.706275,1297.788773,182.009292,...,257727.765870,49.801801,62.709587,12924.714742,22850.505800,0.492732,0.784064,0.550619,0.733963,6.131354
75%,2250.250000,1.487036e+07,2.103804e+07,14079.641695,22424.598839,2774.576420,5520.531338,1381.727937,2213.311950,340.324187,...,381416.629634,64.783787,76.976344,18927.486649,33499.182090,0.748619,1.000000,0.729408,0.899346,132.037426
max,3000.000000,1.999544e+07,3.526011e+07,29269.926629,54578.093316,8317.527382,15193.460738,4969.205532,8550.722397,1869.833226,...,499450.744236,79.963753,99.299629,24991.072823,60813.487769,0.999501,1.000000,0.899488,1.000000,2036.613754

In [12]:
df.dtypes

River_ID                        int64
River_Name                     object
Country                        object
Continent                      object
Population_2015                 int64
Population_2060                 int64
Waste_Generation_2015_tons    float64
Waste_Generation_2060_tons    float64
Plastic_Waste_2015_tons       float64
Plastic_Waste_2060_tons       float64
Mismanaged_Waste_2015_tons    float64
Mismanaged_Waste_2060_tons    float64
Plastic_to_River_2015_tons    float64
Plastic_to_River_2060_tons    float64
River_Length_km               float64
Basin_Area_km2                float64
Urbanization_2015_pct         float64
Urbanization_2060_pct         float64
GDP_per_capita_2015           float64
GDP_per_capita_2060           float64
Policy_Strength_2015          float64
Policy_Strength_2060          float64
Waste_Collection_Rate_2015    float64
Waste_Collection_Rate_2060    float64
Risk_Score_Change             float64
dtype: object

In [13]:
df.isnull().sum()

River_ID                      0
River_Name                    0
Country                       0
Continent                     0
Population_2015               0
Population_2060               0
Waste_Generation_2015_tons    0
Waste_Generation_2060_tons    0
Plastic_Waste_2015_tons       0
Plastic_Waste_2060_tons       0
Mismanaged_Waste_2015_tons    0
Mismanaged_Waste_2060_tons    0
Plastic_to_River_2015_tons    0
Plastic_to_River_2060_tons    0
River_Length_km               0
Basin_Area_km2                0
Urbanization_2015_pct         0
Urbanization_2060_pct         0
GDP_per_capita_2015           0
GDP_per_capita_2060           0
Policy_Strength_2015          0
Policy_Strength_2060          0
Waste_Collection_Rate_2015    0
Waste_Collection_Rate_2060    0
Risk_Score_Change             0
dtype: int64

In [15]:
# Providing shape of the dataset
print("Dataset Shape:", df.shape)

Dataset Shape: (3000, 25)

In [17]:
# Checking the counts for the readmission column
df['Waste_Collection_Rate_2060'].value_counts()

Waste_Collection_Rate_2060
1.000000    340
0.765181      1
0.751059      1
0.627609      1
0.775441      1
           ...
0.869995      1
0.588740      1
0.292095      1
0.559341      1
0.879057      1
Name: count, Length: 2661, dtype: int64